import { RoadmapData } from "@/store/useRoadmapStore";

import frontendDeveloper from "../data/blueprints/frontend-developer.json";
import backendDeveloper from "../data/blueprints/backend-developer.json";
import fullstackDeveloper from "../data/blueprints/fullstack-developer.json";
import devopsEngineer from "../data/blueprints/devops-engineer.json";
import devsecops from "../data/blueprints/devsecops.json";
import dataAnalyst from "../data/blueprints/data-analyst.json";
import aiEngineer from "../data/blueprints/ai-engineer.json";
import aiDataScientist from "../data/blueprints/ai-data-scientist.json";
import dataEngineer from "../data/blueprints/data-engineer.json";
import android from "../data/blueprints/android.json";
import machineLearning from "../data/blueprints/machine-learning.json";
import postgresql from "../data/blueprints/postgresql.json";
import ios from "../data/blueprints/ios.json";
import blockchain from "../data/blueprints/blockchain.json";
import qa from "../data/blueprints/qa.json";
import softwareArchitect from "../data/blueprints/software-architect.json";
import cyberSecurity from "../data/blueprints/cyber-security.json";
import uxDesign from "../data/blueprints/ux-design.json";
import technicalWriter from "../data/blueprints/technical-writer.json";
import gameDeveloper from "../data/blueprints/game-developer.json";
import serverSideGameDeveloper from "../data/blueprints/server-side-game-developer.json";
import mlops from "../data/blueprints/mlops.json";
import productManager from "../data/blueprints/product-manager.json";
import engineeringManager from "../data/blueprints/engineering-manager.json";
import developerRelations from "../data/blueprints/developer-relations.json";
import biAnalyst from "../data/blueprints/bi-analyst.json";
import networkEngineer from "../data/blueprints/network-engineer.json";
import forwardDeployedEngineer from "../data/blueprints/forward-deployed-engineer.json";
import dsa from "../data/blueprints/dsa.json";

export const roadmapBlueprints: Record<string, RoadmapData> = {
  "frontend-developer": frontendDeveloper as RoadmapData,
  "backend-developer": backendDeveloper as RoadmapData,
  "fullstack-developer": fullstackDeveloper as RoadmapData,
  "devops-engineer": devopsEngineer as RoadmapData,
  "devsecops": devsecops as RoadmapData,
  "data-analyst": dataAnalyst as RoadmapData,
  "ai-engineer": aiEngineer as RoadmapData,
  "ai-data-scientist": aiDataScientist as RoadmapData,
  "data-engineer": dataEngineer as RoadmapData,
  "android": android as RoadmapData,
  "machine-learning": machineLearning as RoadmapData,
  "postgresql": postgresql as RoadmapData,
  "ios": ios as RoadmapData,
  "blockchain": blockchain as RoadmapData,
  "qa": qa as RoadmapData,
  "software-architect": softwareArchitect as RoadmapData,
  "cyber-security": cyberSecurity as RoadmapData,
  "ux-design": uxDesign as RoadmapData,
  "technical-writer": technicalWriter as RoadmapData,
  "game-developer": gameDeveloper as RoadmapData,
  "server-side-game-developer": serverSideGameDeveloper as RoadmapData,
  "mlops": mlops as RoadmapData,
  "product-manager": productManager as RoadmapData,
  "engineering-manager": engineeringManager as RoadmapData,
  "developer-relations": developerRelations as RoadmapData,
  "bi-analyst": biAnalyst as RoadmapData,
  "network-engineer": networkEngineer as RoadmapData,
  "forward-deployed-engineer": forwardDeployedEngineer as RoadmapData,
  "dsa": dsa as RoadmapData,
};
